UiPath.PowerShell/Cmdlets/EditProcessSchedule.cs
UiPath.PowerShell/Models/ProcessSchedule.cs
UiPath.PowerShell/UiPath.PowerShell.csproj

This new cmdlet can be used to enable/disable a group of schedules.
I can be used in the following way
`$schedules = Get-UiPathProcessSchedule -AuthToken $token`
`Edit-UiPathProcessSchedule -AuthToken $token -Enabled $false -Ids $([long[]] $schedules.Id) `
or
`Edit-UiPathProcessSchedule -AuthToken $token -Enabled $true -Ids $([long[]] @(1,2,5,6,8,9))`
or
```
$ids = New-Object System.Collections.ArrayList
@(1,2,5,6,8,9) | % { $ids.Add([long]$_) | Out-Null }
Edit-UiPathProcessSchedule -AuthToken $token -Enabled $false -Ids $ids
```
It can operate on only one schedule too:
```
$ids = New-Object System.Collections.ArrayList
@(8) | % { $ids.Add([long]$_) | Out-Null }
Edit-UiPathProcessSchedule -AuthToken $token -Enabled $false -Ids $ids
```

New Cmdlet: Edit-UiPathProcessSchedule 

---

UiPath.PowerShell/Cmdlets/GetPackage.cs
docs/Edit-UiPathProcessSchedule.md
docs/Get-UiPathPackage.md
docs/Home.md

- Change the base class of the cmdlet
- Make Id a `string` filterable property
Fixes #11
```
PS C:\Users\remus.rusanu> Get-UiPathPackage -Id 'No-op'
Id              : No-op
IsActive        : False
IsLatestVersion : True
Key             : No-op:1.0.6837.27201
OldVersion      :
Published       : 9/20/2018 12:06:44 PM
Title           :
Version         : 1.0.6837.27201
Description     : Blank Project
```

Get-UiPathPackage -Id <string>

---

UiPath.Web.Client/UiPath.Web.Client.csproj

It works better with VS, intellisense et all

Change Generated code to 'Visible' in csproj

---

UiPath.PowerShell/Cmdlets/GetPackageVersion.cs
UiPath.PowerShell/Cmdlets/Nouns.cs
UiPath.PowerShell/Cmdlets/UpdateProcess.cs
UiPath.PowerShell/UiPath.PowerShell.csproj
docs/Get-UiPathPackageVersion.md
docs/Home.md
docs/Update-UiPathProcess.md

New cmdlets:
- Get-UiPathPackageVersion lists the versions of a package
- Update-UiPathProcess can change the versionof a package, supports
'latest' and 'rollback'
Fixes #9

Package Versions

---

UiPath.PowerShell/Util/AuthenticatedCmdlet.cs
UiPath.Web.Client/IUiPathWebApi.cs
UiPath.Web.Client/UiPath.Web.Client.csproj
UiPath.Web.Client/UiPathWebApi.cs

Cleanup the duplicate code around various `MakeApi`

Better MakeApi

---

UiPath.PowerShell/Util/AuthenticatedCmdlet.cs
UiPath.PowerShell/Util/OrchestratorProtocolVersion.cs
UiPath.Web.Client/Swagger/UiPath2018.4.0.swagger
UiPath.Web.Client/UiPath.Web.Client.csproj
UiPath.Web.Client/UiPathWebApi.cs

Not used, just added to allow 18.4 specific features.

Add the 18.4 swagger, client and WebAPI

---

Examples/Get-UiPathPackageDependencies.ps1
UiPath.Orchestrator.Powershell.sln
UiPath.PowerShell/Cmdlets/GetAuthToken.cs
UiPath.PowerShell/Cmdlets/GetSettings.cs
UiPath.PowerShell/Cmdlets/Nouns.cs
UiPath.PowerShell/Models/AuthToken.cs
UiPath.PowerShell/Models/Setting.cs
UiPath.PowerShell/UiPath.PowerShell.csproj
UiPath.PowerShell/Util/AuthenticatedCmdlet.cs
UiPath.PowerShell/Util/KeyValuePairConverter.cs
docs/Get-UiPathAuthToken.md
docs/Get-UiPathSetting.md
docs/Home.md

- require token suport (`-CurrentSession`, `$_.TenantName` etc)
- required GetSettings support (for deployment URL)
- example that download nuspec, parses dependencies

Get-UiPathPackageDependencies example script

---

UiPath.PowerShell/UiPath.PowerShell.csproj
UiPath.PowerShell/Util/BindingResolver.cs
UiPath.PowerShell/Util/SecurityProtocolFix.cs
UiPath.PowerShell/Util/UiPathCmdlet.cs

Force default TLS protocol 1.1 and 1.2, don't accept Ssl3 and 1.0

---

UiPath.PowerShell/Cmdlets/EditRobot.cs
UiPath.PowerShell/Util/KeyValuePairConverter.cs

Fix the KeyValuePairConverter not to clain it can convert System.Object

---

UiPath.PowerShell/Cmdlets/AddRobot.cs
UiPath.PowerShell/Models/Robot.cs
UiPath.PowerShell/Util/UiPathCmdlet.cs
docs/Add-UiPathRobot.md

18.4 Orchestrators support Smartcard based login and this adds the required support in the Add-UiPathUser cmdlet (als Get-UiPathUser filter)

Add support for CredentialType Password/SmartCard

---

Examples/Sync-UiPathADUsers.ps1

Add Lock action for orphane users
Add new parameter AllowAllDomainNames that will enable the import of all groups & users from sub domains

Add Lock for OrphanedUsersAction and AllowAllDomainNames param

---

.vsts-ci.yml
Properties/GlobalAssemblyInfo.cs
UiPath.PowerShell/Cmdlets/GetEnvironmentRobot.cs
UiPath.PowerShell/UiPath.PowerShell.csproj
docs/Get-UiPathEnvironmentRobot.md
docs/Home.md

Add Get-UiPathEnvironmentRobot

---

.vsts-ci.yml
UiPath.PowerShell.nuspec

Add .symbols. nuspec and build step

---

Examples/Sync-UiPathADUsers.ps1

Add removed `$op=$operations[$adUserName]`

---

UiPath.PowerShell/Cmdlets/AddRobot.cs

Fix Type -> HostingType in Addrobot

---

UiPath.PowerShell/Cmdlets/GetAsset.cs
UiPath.PowerShell/Cmdlets/GetEnvironment.cs
UiPath.PowerShell/Cmdlets/GetJob.cs
UiPath.PowerShell/Cmdlets/GetLibrary.cs
UiPath.PowerShell/Cmdlets/GetLibraryVersion.cs
UiPath.PowerShell/Cmdlets/GetMachine.cs
UiPath.PowerShell/Cmdlets/GetOrganizationUnit.cs
UiPath.PowerShell/Cmdlets/GetPackage.cs
UiPath.PowerShell/Cmdlets/GetProcess.cs
UiPath.PowerShell/Cmdlets/GetProcessSchedule.cs
UiPath.PowerShell/Cmdlets/GetQueueDefinition.cs
UiPath.PowerShell/Cmdlets/GetRobot.cs
UiPath.PowerShell/Cmdlets/GetSettings.cs
UiPath.PowerShell/Cmdlets/GetTenant.cs
UiPath.PowerShell/Cmdlets/GetUser.cs
UiPath.PowerShell/Cmdlets/GetWebhook.cs
UiPath.PowerShell/Util/FilteredBaseCmdlet.cs
UiPath.PowerShell/Util/FilteredIdCmdlet.cs
UiPath.Web.Client/Extensions/ODataExtensions.cs
UiPath.Web.Client/UiPath.Web.Client.csproj

Paging support on Get-UiPathXXX

---

UiPath.PowerShell/Util/FilteredBaseCmdlet.cs
UiPath.PowerShell/Util/FilteredIdCmdlet.cs
docs/Get-UiPathAsset.md
docs/Get-UiPathEnvironment.md
docs/Get-UiPathJob.md
docs/Get-UiPathLibrary.md
docs/Get-UiPathLibraryVersion.md
docs/Get-UiPathMachine.md
docs/Get-UiPathOrganizationUnit.md
docs/Get-UiPathPackage.md
docs/Get-UiPathPermission.md
docs/Get-UiPathProcess.md
docs/Get-UiPathProcessSchedule.md
docs/Get-UiPathQueueDefinition.md
docs/Get-UiPathRobot.md
docs/Get-UiPathRobotSettings.md
docs/Get-UiPathRole.md
docs/Get-UiPathSetting.md
docs/Get-UiPathTenant.md
docs/Get-UiPathUser.md
docs/Get-UiPathWebhook.md

Make paging optional. Fixes #77

Make paging optional. Fixes #77

---

UiPath.PowerShell/Util/FilteredBaseCmdlet.cs

Fix pagination

---

UiPath.PowerShell/Cmdlets/AddLibrary.cs
UiPath.PowerShell/Util/OrchestratorProtocolVersion.cs

The 19.10 UploadPackage changed the response status to 207 and this
breaks the 18.3 client.
Fixes #87

Use client 19.10 for add-library if server is 19.10

---

Examples/Add-UiPathDefaultRoles.ps1

[Issue](https://github.com/UiPath/orchestrator-powershell/pull/73#issuecomment-645340539)

Default Roles: Fix permissions not being added to created roles

---

UiPath.PowerShell/Cmdlets/GetCredentialStore.cs
UiPath.PowerShell/Cmdlets/Nouns.cs
UiPath.PowerShell/Models/CredentialStore.cs
UiPath.Web.Client/Extensions/ODataExtensions.cs
docs/Get-UiPathCredentialStore.md
docs/Home.md

Minimal support, only Get and Get Default, needed for Buckets branch later

19.10 credential stores support

---

UiPath.PowerShell/UiPath.BindingResolve.ps1

Seems that leavind the AssemblyResolve handler is dangerous as it leads
to random SO. This fix forces the module load and binding resolve (by
enumerating all possible types in the module)
Fixes #127

Fix possible stackoverflow in binding redirect script

---

UiPath.PowerShell/Cmdlets/GetJob.cs
UiPath.PowerShell/Cmdlets/GetProcess.cs
UiPath.PowerShell/Cmdlets/StartJob.cs
UiPath.PowerShell/Models/Job.cs
UiPath.PowerShell/Models/Process.cs
UiPath.PowerShell/Util/AutoMapper.cs
UiPath.Web.Client/Extensions/ODataExtensions.cs
docs/Get-UiPathJob.md
docs/Start-UiPathJob.md

- Add `-InputArguments @{name=value;name=value}` to `Start-UiPathJob`
- Add InputArguments, OutputArguments to `Get-UiPathJob` output
- Add Arguments to `Get-UiPathProcess` output
Fixes #129

Support Input Arguments for jobs

---

UiPath.PowerShell/Cmdlets/GetAuthToken.cs
docs/Get-UiPathAuthToken.md

Do not add Default FolderName if host login

Fix Host login

---

UiPath.PowerShell/Cmdlets/AddProcess.cs
UiPath.PowerShell/Cmdlets/GetProcess.cs
UiPath.PowerShell/Models/Folder.cs
UiPath.PowerShell/Models/Process.cs
UiPath.PowerShell/Util/AutoMapper.cs
UiPath.PowerShell/Util/UiPathCmdlet.cs
UiPath.Web.Client/Extensions/ODataExtensions.cs
docs/Add-UiPathProcess.md

- Make Environment optional, for Modern folders
- parse Process settings on -Id Get (tried to add Add support but run
into camelCase/PascalCase swagger BS)
fixes #138

AddProcess and GetProcess fixes

---

UiPath.PowerShell/Cmdlets/GetCurrentUserFolders.cs
UiPath.PowerShell/Cmdlets/GetFolderUsers.cs
UiPath.PowerShell/Cmdlets/GetMaintenance.cs
UiPath.PowerShell/Cmdlets/NewAssetRobotValue.cs
UiPath.PowerShell/Models/Asset.cs
UiPath.PowerShell/Models/AssetRobotValue.cs
UiPath.PowerShell/Models/Environment.cs
UiPath.PowerShell/Models/ExtendedFolder.cs
UiPath.PowerShell/Models/Folder.cs
UiPath.PowerShell/Models/Job.cs
UiPath.PowerShell/Models/MachineFolder.cs
UiPath.PowerShell/Models/QueueItem.cs
UiPath.PowerShell/Models/Setting.cs
UiPath.PowerShell/Models/UserRole.cs
UiPath.PowerShell/Models/Webhook.cs
UiPath.PowerShell/Util/AutoMapper.cs
docs/Get-UiPathFolderUsers.md

Fix auto-rest types leak into Posh models

---

.vsts-ci.yml
UiPath.PowerShell/Cmdlets/GetAuthToken.cs
UiPath.PowerShell/Models/AuthToken.cs
UiPath.PowerShell/Models/CloudDeployments.cs

Check if URL is Cloud URL

---

UiPath.PowerShell/OAuth/LoginForm.cs
UiPath.PowerShell/Util/RestVerboseTracer.cs
UiPath.PowerShell/Util/UiPathCmdlet.cs

Make WebBrowser render the document and follow the OAuth

Add IE tags to uipath returned documents

---

UiPath.PowerShell/Cmdlets/AddProcessSchedule.cs
UiPath.PowerShell/Cmdlets/GetProcessSchedule.cs
UiPath.PowerShell/Models/ProcessSchedule.cs
UiPath.PowerShell/Util/AutoMapper.cs
UiPath.Web.Client/Extensions/ODataExtensions.cs
docs/Add-UiPathProcessSchedule.md

Suuport queue triggers in classic folders (19.10)
